config/routes.rb
Tenancy::Application.routes.draw do
  resources :routines

  resources :assets

  resources :items

  devise_for :users

  authenticated :user do
    root :to => 'home#index'
  end

  unauthenticated :user do
    root :to => redirect("/users/sign_in")
  end

  resources :users, :only => [:show, :index]
end

app/models/routine.rb
class Routine < ActiveRecord::Base
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_filter :authenticate_user!

  # GET /routines
  # GET /routines.json
  def index
    @routines = Routine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @routines }
    end
  end

  # GET /routines/1
  # GET /routines/1.json
  def show
    @routine = Routine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @routine }
    end
  end

  # GET /routines/new
  # GET /routines/new.json
  def new
    @routine = Routine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @routine }
    end
  end

  # GET /routines/1/edit
  def edit
    @routine = Routine.find(params[:id])
  end

  # POST /routines
  # POST /routines.json
  def create
    @routine = Routine.new(params[:routine])

    respond_to do |format|
      if @routine.save
        format.html { redirect_to @routine, notice: 'Routine was successfully created.' }
        format.json { render json: @routine, status: :created, location: @routine }
      else
        format.html { render action: "new" }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /routines/1
  # PUT /routines/1.json
  def update
    @routine = Routine.find(params[:id])

    respond_to do |format|
      if @routine.update_attributes(params[:routine])
        format.html { redirect_to @routine, notice: 'Routine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routines/1
  # DELETE /routines/1.json
  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy

    respond_to do |format|
      format.html { redirect_to routines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_form.html.haml
= form_for @routine, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :category, :class => 'control-label'
    .controls
      = f.text_field :category, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), routines_path, :class => 'btn'

app/views/routines/edit.html.haml
- model_class = @routine.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/routines/index.html.haml
- model_class = Routine.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @routines.each do |routine|
      %tr
        %td= link_to routine.id, routine_path(routine)
        %td= routine.name
        %td= routine.category
        %td= routine.description
        %td=l routine.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_routine_path(routine), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), routine_path(routine), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_routine_path, :class => 'btn btn-primary'

app/views/routines/new.html.haml
- model_class = @routine.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/routines/show.html.haml
- model_class = @routine.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @routine.name
%p
  %strong= model_class.human_attribute_name(:category) + ':'
  %br
  = @routine.category
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @routine.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), routines_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_routine_path(@routine), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), routine_path(@routine), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'