config/routes.rb
Tenancy::Application.routes.draw do
  resources :routines

  resources :assets

  resources :items

  devise_for :users

  authenticated :user do
    root :to => 'home#index'
  end

  unauthenticated :user do
    root :to => redirect("/users/sign_in")
  end

  resources :users, :only => [:show, :index]
end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.haml
= form_for @asset, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :asset_code, :class => 'control-label'
    .controls
      = f.text_field :asset_code, :class => 'text_field'
  .control-group
    = f.label :category, :class => 'control-label'
    .controls
      = f.text_field :category, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :latitude, :class => 'control-label'
    .controls
      = f.text_field :latitude, :class => 'text_field'
  .control-group
    = f.label :longitude, :class => 'control-label'
    .controls
      = f.text_field :longitude, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), assets_path, :class => 'btn'

app/views/assets/edit.html.haml
- model_class = @asset.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/assets/index.html.haml
- model_class = Asset.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:asset_code)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:latitude)
      %th= model_class.human_attribute_name(:longitude)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @assets.each do |asset|
      %tr
        %td= link_to asset.id, asset_path(asset)
        %td= asset.asset_code
        %td= asset.category
        %td= asset.description
        %td= asset.latitude
        %td= asset.longitude
        %td=l asset.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_asset_path(asset), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), asset_path(asset), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_asset_path, :class => 'btn btn-primary'

app/views/assets/new.html.haml
- model_class = @asset.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/assets/show.html.haml
- model_class = @asset.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:asset_code) + ':'
  %br
  = @asset.asset_code
%p
  %strong= model_class.human_attribute_name(:category) + ':'
  %br
  = @asset.category
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @asset.description
%p
  %strong= model_class.human_attribute_name(:latitude) + ':'
  %br
  = @asset.latitude
%p
  %strong= model_class.human_attribute_name(:longitude) + ':'
  %br
  = @asset.longitude

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), assets_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_asset_path(@asset), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), asset_path(@asset), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'