config/routes.rb
Tenancy::Application.routes.draw do
  resources :routines

  resources :assets

  resources :items

  devise_for :users

  authenticated :user do
    root :to => 'home#index'
  end

  unauthenticated :user do
    root :to => redirect("/users/sign_in")
  end

  resources :users, :only => [:show, :index]
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :item_code, :class => 'control-label'
    .controls
      = f.text_field :item_code, :class => 'text_field'
  .control-group
    = f.label :category, :class => 'control-label'
    .controls
      = f.text_field :category, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :latitude, :class => 'control-label'
    .controls
      = f.text_field :latitude, :class => 'text_field'
  .control-group
    = f.label :longitude, :class => 'control-label'
    .controls
      = f.text_field :longitude, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), items_path, :class => 'btn'

app/views/items/edit.html.haml
- model_class = @item.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/items/index.html.haml
- model_class = Item.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:item_code)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:latitude)
      %th= model_class.human_attribute_name(:longitude)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @items.each do |item|
      %tr
        %td= link_to item.id, item_path(item)
        %td= item.item_code
        %td= item.category
        %td= item.description
        %td= item.latitude
        %td= item.longitude
        %td=l item.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(item), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(item), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_item_path, :class => 'btn btn-primary'

app/views/items/new.html.haml
- model_class = @item.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/items/show.html.haml
- model_class = @item.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:item_code) + ':'
  %br
  = @item.item_code
%p
  %strong= model_class.human_attribute_name(:category) + ':'
  %br
  = @item.category
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @item.description
%p
  %strong= model_class.human_attribute_name(:latitude) + ':'
  %br
  = @item.latitude
%p
  %strong= model_class.human_attribute_name(:longitude) + ':'
  %br
  = @item.longitude

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), items_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(@item), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(@item), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'