config/routes.rb
Tenancy::Application.routes.draw do
  resources :routines

  resources :assets

  resources :items

  devise_for :users

  authenticated :user do
    root :to => 'home#index'
  end

  unauthenticated :user do
    root :to => redirect("/users/sign_in")
  end

  resources :users, :only => [:show, :index]
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - puts "message: "+msg
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Tenancy", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
    - if current_user.has_role? :admin
      %li
        = link_to('Admin', users_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/_sidebar.html.haml
- if user_signed_in?
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header Manage
      - if current_user.has_role? :admin
        %li= link_to('Users', users_path)
        %li= link_to "Items", items_path
        %li= link_to "Routines", routines_path
      - if current_user.has_role? :executive
        %li= link_to "Reports", root_path
      - if current_user.has_role? :manager
        %li= link_to "Items", items_path
        %li= link_to "Routines", routines_path
        %li= link_to "Issues", root_path
        %li= link_to "Work Orders", root_path
        %li= link_to "Purchase Orders", root_path
      - if current_user.has_role? :technician
        %li= link_to "Items", items_path
        %li= link_to "Routines", routines_path
        %li= link_to "Issues", root_path
        %li= link_to "Work Orders", root_path
      - if current_user.has_role? :user
        %li= link_to "Issues", root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Tenancy"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              -#= yield
          .row
            .span3
              = render 'layouts/sidebar'
            .span9
              = yield
          %footer
            %p
            %p &copy; gRokkLab 2012